### ISSUE TITLE
The `My Avatar` at http://ddbullfrog.github.io/iCard-Resume/ is broken

### ISSUE THREAD

**Issue by archersmind** [ddbullfrog/resumecard#4]
Hi,

The `My Avatar` at http://ddbullfrog.github.io/iCard-Resume/ is broken.
Can you please check it ?

![screenshot from 2015-09-25 13 41 22](https://cloud.githubusercontent.com/assets/1461331/10093908/b99c5aba-638b-11e5-9247-b895b378aaa2.png)

**Comment by ddbullfrog** [comment]
fixed
