### ISSUE TITLE
当浏览器窗口的宽度很小时，社交信息隐藏掉了

### ISSUE THREAD

**Issue by liungkejin** [ddbullfrog/resumecard#8]
在手机上浏览，或者浏览器的宽度很小时，社交信息没有自动的移动下方，而是被隐藏掉了， 而下面的内容显示正常。
我对比了一下， 我把 `header.html` 里面所对应的 `div`的 `class`， 即`<div class="col-sm-4 visible-md-block visible-lg-block visible-sm-block">`修改为 `<div class="col-sm-4">`， 就显示正常了。
但是我不怎么懂html/css, 只是对比了一下代码，希望你可以完美修复一下，谢谢！

**Comment by ddbullfrog** [comment]
使用了 responsive design， 当用手机浏览器 故意不让社交信息显示， 如果你希望显示， 可以自行修改自己的theme。

**Comment by liungkejin** [comment]
哦哦， 好的！谢谢
